name: Kubo PDF Viewer Deploy - Staging

on:
  push:
    tags:
      - "v*.*.*_staging"

env:
  SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}

jobs:
  setup-build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm

      - name: Install Gulp
        run: npm install -g gulp-cli

      - name: Install other dependencies
        run: npm install -f

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.DEPLOY_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEPLOY_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build generic & generic-legacy
        run: npm run build:all

      - name: Copy files to S3
        run: |
          aws s3 sync dist/ s3://us-east-1-kubo-pdf-viewer-staging

      - name: Clear the CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id E1441TC0LOPWSN --paths '/*'

  slack-workflow-status:
    if: always()
    name: Post Workflow Status
    needs:
      - setup-build-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@v1.2.0
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{env.SLACK_WEBHOOK_URL}}
          include_jobs: true
